const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv/config");

const server = express();
const bandeRoute = require("./routes/bande");
const entrerBandeRoute = require("./routes/entréeBande");
const batimentRoute = require("./routes/batiment");
const clientRoute = require("./routes/client");
const depenseRoute = require("./routes/depense");
const eauRoute = require("./routes/eau");
const entrerNutritionRoute = require("./routes/entrerNutrition");
const entrerMaterialRoute = require("./routes/entrerMaterial");
const fermeRoute = require("./routes/ferme");
const fournisseurRoute = require("./routes/fournisseur");
const materielRoute = require("./routes/materiel");
const perteRoute = require("./routes/perte");
const typePerteBRoute = require("./routes/typePerteB");
const typePerteMRoute = require("./routes/typePerteM");
const typePerteNRoute = require("./routes/typePerteN");
const typePertePRoute = require("./routes/typePerteP");
const typePerteTRoute = require("./routes/typePerteT");
const naissanceRoute = require("./routes/naissance");
const nutritionRoute = require("./routes/nutrition");
const ouvrierRoute = require("./routes/ouvrier");
const ponteRoute = require("./routes/ponte");
const poussinJourRoute = require("./routes/poussinJour");
const ramassageOeufRoute = require("./routes/ramassageOeuf");
const sortieMaterielRoute = require("./routes/sortieMateriel");
const sortieNutritionRoute = require("./routes/sortieNutrition");
const sortieOeufRoute = require("./routes/sortieOeuf");
const utilisateurRoute = require("./routes/utilisateur");
const uniteCapaciteRoute = require("./routes/uniteCapacite");
const venteRoute = require("./routes/vente");
const venteOeufRoute = require("./routes/venteOeuf");
const venteBandeRoute = require("./routes/venteBande");
const veterinaireRoute = require("./routes/veterinaire");
const vaccinationRoute = require("./routes/vaccination");
const observationVétérinaireRoute = require("./routes/observationVétérinaire");
const observationFéconditéRoute = require("./routes/observationFécondité");

server.use(express.json());
server.use(cors());

server.get("/", (req, res) => {
  res.send("bonsoir LOUIS");
});

server.use("/api/bande", bandeRoute);
server.use("/api/entrerBande", entrerBandeRoute);
server.use("/api/batiment", batimentRoute);
server.use("/api/client", clientRoute);
server.use("/api/depense", depenseRoute);
server.use("/api/eau", eauRoute);
server.use("/api/entrerNutrition", entrerNutritionRoute);
server.use("/api/entrerMateriel", entrerMaterialRoute);
server.use("/api/ferme", fermeRoute);
server.use("/api/fournisseur", fournisseurRoute);
server.use("/api/materiel", materielRoute);
server.use("/api/perte", perteRoute);
server.use("/api/typePerteB", typePerteBRoute);
server.use("/api/typePerteM", typePerteMRoute);
server.use("/api/typePerteN", typePerteNRoute);
server.use("/api/typePerteP", typePertePRoute);
server.use("/api/typePerteT", typePerteTRoute);
server.use("/api/naissance", naissanceRoute);
server.use("/api/nutrition", nutritionRoute);
server.use("/api/ouvrier", ouvrierRoute);
server.use("/api/ponte", ponteRoute);
server.use("/api/poussinJour", poussinJourRoute);
server.use("/api/ramassageOeuf", ramassageOeufRoute);
server.use("/api/sortieMateriel", sortieMaterielRoute);
server.use("/api/sortieNutrition", sortieNutritionRoute);
server.use("/api/sortieOeuf", sortieOeufRoute);
server.use("/api/utilisateur", utilisateurRoute);
server.use("/api/uniteCapacite", uniteCapaciteRoute);
server.use("/api/vente", venteRoute);
server.use("/api/venteOeuf", venteOeufRoute);
server.use("/api/venteBande", venteBandeRoute);
server.use("/api/veterinaire", veterinaireRoute);
server.use("/api/vaccination", vaccinationRoute);
server.use("/api/observationVeterinaire", observationVétérinaireRoute);
server.use("/api/observationFecondite", observationFéconditéRoute);

server.listen(process.env.SERVER_PORT);
